Work section
App-Developer8866/portfolio-project pull request #2
Opened 2022-10-28 13:35 UTC by App-Developer8866

I have done the work section of my portfolio project on microverse of the first week.

2022-10-28 15:55 UTC, codecaiine requested changes
Hi @App-Developer8866 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Great project implementation :heavy_check_mark: 
- No linters errors :heavy_check_mark: 
- Great ui design :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 15:55 UTC, codecaiine commented on index.html
> +        <div class="social_media"><a href="#">LET’S CONNECT</a></div>
- [ ] Good job but I think it is better to use a `hx` tag instead of a tag to represent the hierarchical structure makes it easier for users to digest content. Please fix it :smile:

2022-10-28 15:55 UTC, codecaiine commented on index.html
> +        </ul>
- [ ] Good job so far by using ul for The technology categories and technology but I think you can refactor this code and make it syntactically correct. You can see the example below :arrow_down:  Please Fix it :+1: 

```
<ul>
  <li>Languages
    <ul>
      <li>javascript</li>
      <li>HTML</li>
      <li>CSS</li>
    </ul>
  </li>
  <li>Frameworks</li>
  <li>Skills</li>
</ul>

```

2022-10-28 15:55 UTC, codecaiine commented on style.css
> +}
- [ ] Good job so far, your project card design is good but there are a few things you need to work on. From the project requirement, your work section needs to have the margins (top, bottom, left, right) as defined in the chosen design :smile:  Please fix it in order to make it similar to the Figma template. Please check the screenshots below :arrow_down: to see the differences. 

#### Your design
![Screenshot from 2022-10-28 14-48-03](https://user-images.githubusercontent.com/6615394/198672839-06649d78-ab12-4c88-bed3-e230a30fb556.jpg)

#### Figma template
![Screenshot from 2022-10-28 14-46-59](https://user-images.githubusercontent.com/6615394/198672874-b071c2d2-9f3c-41a3-8544-4e7b85548056.png)

- [ ] Please make sure to have the same background template for your work section background color `grey` in order to make it similar to the Figma template :+1:

2022-10-28 15:55 UTC, codecaiine commented on style.css
> +}
- [ ] Good job so far with the about yourself section But I think you can improve your about yourself section by using the correct spacing (Padding/Margin) as defined on the Figma template in order to make your website similar to it. It is very important for a developer to pay attention to details :smile: 

- [ ] Please make sure that your social media icons design is similar to Figma template :+1: 
 
#### Your design
![Screenshot from 2022-10-28 15-22-00](https://user-images.githubusercontent.com/6615394/198677444-fce7caa6-3a0c-4452-a45d-24d7632ef369.jpg)

#### Figma design
![Screenshot from 2022-10-28 15-38-41](https://user-images.githubusercontent.com/6615394/198677670-aae9502b-339a-4f78-8179-3fb9a7d60e12.png)

2022-10-28 15:55 UTC, codecaiine commented on style.css
> +.skills {
- [ ] Good job so far But I noticed that your design is a little bit different from the Figma template. Please make sure that your technology title has the same `font size` as defined on the Figma template. Also, don't forget to have the same arrow icons as defined in the Figma design. :+1: 

- [ ] I also noticed that your design is different from the Figma template. Please make sure that you stick to the Figma design as much as possible. As a developer it is very important to pay attention to the details :+1:  
Please check the screenshots below to see the differences between your design and Figma :arrow_down: 

#### Your design
![Screenshot from 2022-10-28 15-41-24(1)](https://user-images.githubusercontent.com/6615394/198680111-974f4b15-3240-4f72-950f-de813c6842d2.jpg)

#### Figma design
![Screenshot from 2022-10-28 15-52-32](https://user-images.githubusercontent.com/6615394/198680419-3116ccc2-b676-467b-a60e-880e78fad732.png)

2022-10-29 16:06 UTC, MoRaad97 requested changes
Hi @App-Developer8866 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 16:06 UTC, MoRaad97 commented on style.css
> +
- [ ]  Please fix the issue, you can try to delete the width:30vw.
![ScreenShot_20221029190249](https://user-images.githubusercontent.com/89518488/198841444-482256af-103b-468b-802b-ba4e9c89051a.png)

2022-10-29 16:45 UTC, algerina approved these changes
Hi @App-Developer8866 , 
Good job so far!

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 
<img src="https://media2.giphy.com/media/2MQi4hG5NBBFCXdKnR/giphy.gif"/>

 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina  if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-10-29 16:47 UTC, merged